version: '3.8'

services:
  # This file provides the secrets infrastructure for the memory system
  
  # Vault for storing secrets
  vault:
    image: vault:latest
    container_name: tori-secrets-vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=tori-dev-token
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    volumes:
      - vault-data:/vault/data
      - ./.secrets:/secrets
    command: server -dev
    networks:
      - tori-memory-net

  # Configures services to use secrets
  secrets-config:
    image: alpine:latest
    container_name: tori-secrets-config
    depends_on:
      - vault
    volumes:
      - ./.secrets:/secrets
    command: >
      sh -c "
        # Wait for vault
        sleep 5
        
        # If we have an API key file, use it
        if [ -f /secrets/api_key.txt ]; then
          export API_KEY=$(cat /secrets/api_key.txt)
          echo 'Using API key from file'
        else
          export API_KEY='development-key-placeholder'
          echo 'Using placeholder API key'
        fi
        
        # Output success message
        echo 'Secrets configured successfully'
        
        # Keep container alive during debugging
        sleep 10
      "
    networks:
      - tori-memory-net

networks:
  tori-memory-net:
    external: true

volumes:
  vault-data:
