# Prometheus configuration for TORI Memory Consolidation System
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alerts/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "episodic-vault"
    scrape_interval: 10s
    static_configs:
      - targets: ["episodic-vault:9091"]
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: service
        replacement: "episodic_vault"

  - job_name: "sleep-scheduler"
    scrape_interval: 10s
    static_configs:
      - targets: ["sleep-scheduler:9092"]
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: service
        replacement: "sleep_scheduler"

  - job_name: "sparse-pruner"
    scrape_interval: 10s
    static_configs:
      - targets: ["sparse-pruner:9093"]
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: service
        replacement: "sparse_pruner"

  - job_name: "koopman-learner"
    scrape_interval: 10s
    static_configs:
      - targets: ["koopman-learner:9094"]
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: service
        replacement: "koopman_learner"
